# https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix
version: '3'

# https://docs.docker.com/compose/compose-file/#service-configuration-reference
services:

  # Postgres image
  # Configuration:
  #   - Bind the data storage location to our own directory
  postgres:
    image: "postgres:latest"
    ports:
      - 5432:5432
    volumes: 
      - ./docker-volumes/var/lib/postgresql/data:/var/lib/postgresql/data

  devcamp-backend:
    build: .
    command: ["./wait-for-it.sh", "postgres:5432", "--", "go", "run", "app.go"]
    volumes:
      - .:/go/src/github.com/martinock/devcamp-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres